### ISSUE TITLE
Question: How to add custom validation rule?

### ISSUE THREAD

**Issue by tmtben** [dupkey/slim3-api#1]
Hello,

I've been using the "respect\validation" part of your skeleton.

I try to add my own custom rule (ie: check email's user is not already used into DB), but it fails.
I have this kind of Slim error:
"newRule is not a valid rule name".

I think the "with" attribute has no effect or my new classes are not loaded by Slim...

This is not my code, but it's pretty similar:
https://github.com/ArneAnka/slim-test/tree/master/app/Validation

Did you manage to do so with your skeleton?

Best regards,
Ben

**Comment by nicgene** [comment]
It's hard to know without seeing your code.

Typically, I only validate input to make sure it's the right format. I normally do checks against the database inside of my controller/action/domain.

https://github.com/dupkey/slim3-api/blob/f386ba33f0d918f69795b53d6f93b74b388bb6e1/app/src/Actions/Users/CreateUser.php#L60

**Comment by tmtben** [comment]
Thanks @dupkey for your quick answer.

I finally managed to make my own respect\validation rule works.

I misunderstood the usage of the "with" instruction documented here:
https://respect-validation.readthedocs.io/en/1.1/feature-guide/#custom-rules

In my case, these following instructions must be added globally inside my Slim "dependencies" file:
use Respect\Validation\Validator as v;
v::with('App\\Validation\\Rules');

I was trying to add them locally inside my controller but it was not enough.

See you,
Ben

**Comment by nicgene** [comment]
That makes sense, glad you got it working.

I tend to forget that using Pimple for DI one must wire up all their dependencies. If you want autowiring you can check out [PHP-DI](http://php-di.org/)
